name: Setup # Inspired by https://github.com/pyg-team/pytorch_geometric/blob/737707c37fc2bd712a2289b683ec14549926ff49/.github/actions/setup/action.yml

description: Set up Python, PyTorch and PyTorch Geometric.

inputs: # defaults are set to the version used in the dev container
  python-version:
    required: false
    default: "3.10"
    description: "The Python version to use."
  cuda-version:
    required: false
    default: cpu # For GPU support a self-hosted runner is required.
    description: "If CUDA should be used or not."

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true

    - name: Install manim dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg
      shell: bash

    - name: Install pathpyG
      run: |
        uv sync --frozen --extra vis --extra ${{ inputs.cuda-version }}
      shell: bash

    - name: Check installation
      run: |
        uv run python -c "import torch; print('PyTorch:', torch.__version__)"
        uv run python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        uv run python -c "import torch; print('CUDA:', torch.version.cuda)"
      shell: bash
