[loggers]
keys=root,pathpyg

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=simpleFormatter, customFormatter

[logger_root]
level=ERROR
handlers=consoleHandler,fileHandler

[logger_pathpyg]
level=INFO
handlers=consoleHandler,fileHandler
qualname=pathpyg
propagate=0

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=customFormatter
args=('pathpyG.log', )

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=customFormatter
args=(sys.stdout,)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s

[formatter_customFormatter]
format=%(asctime)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
