# Inspired by https://github.com/pyg-team/pytorch_geometric/blob/ee30973ed0957a7f29f345d4eeaf9cfd70805109/.github/workflows/testing.yml
name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Only run workflow if certain files have been changed.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            .github/workflows/testing.yml
            src/**
            tests/**
            pyproject.toml

      - name: Setup packages
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/setup

      - name: Install main package
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pip install -e .[test]

      - name: Run tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pytest
